notifications:
    email: false

language: python
cache: pip
python:
  - "3.6"

services:
  - mysql

install:
  - pip install poetry
  - poetry install

jobs:
  include:
    - stage: lint
      script:
        - poetry run black --check .
        - poetry run flake8 .
    - stage: test
      script:
        - mysql -e 'create database working_bikes;'
        - poetry run python manage.py migrate
        - poetry run python manage.py collectstatic --noinput
        - poetry run pytest --cov
