language: python
python:
  - "3.4"
  - "3.5"
script:
  - python manage.py test --noinput
before_script:
  - mysql -e 'create database working_bikes;'
  - python manage.py migrate
  - python manage.py collectstatic --noinput
