language: python
python:
  - "3.4"
  - "3.5"
script:
  - python manage.py test --noinput
install:
  - pip install six && pip install -r dev-requirements.txt
before_script:
  - mysql -e 'create database working_bikes;'
  - python manage.py migrate
  - python manage.py collectstatic --noinput
