language: python
cache: pip
python:
  - "3.4"
  - "3.5"
script:
  - coverage run --source='.' manage.py test --noinput && coverage report
install:
  - pip install six && pip install -r dev-requirements.txt
before_script:
  - mysql -e 'create database working_bikes;'
  - python manage.py migrate
  - python manage.py collectstatic --noinput
